require:
  - rubocop-rspec
  - rubocop-performance

inherit_gem:
  rentacop:
    - rentacop.yml
    - rspec.yml

AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  Exclude:
    - 'dev/**/*'

# Allow methods that start with `get_` in some cases
Naming/AccessorMethodName:
  Exclude:
    - 'spec/fixtures/**/*'
