require:
  - rubocop-rspec
  - rubocop-performance

inherit_gem:
  rentacop: rentacop.yml

AllCops:
  TargetRubyVersion: 2.7.0
  Exclude:
    - 'debug.rb'
    - 'dev/**/*'

# Allow methods that start with `get_` in some cases
Naming/AccessorMethodName:
  Exclude:
    - 'spec/fixtures/**/*'

# Prefer `receive` over `have_received`spies
RSpec/MessageSpies:
  EnforcedStyle: receive

# Allow multiple expectations per block
RSpec/MultipleExpectations:
  Max: 3

# Allow calling `subject` explicitly
RSpec/NamedSubject:
  EnforcedStyle: named_only

# Allow stubbing other `subject` methods
RSpec/SubjectStub:
  Enabled: false

# Allow unnamed doubles
RSpec/VerifiedDoubles:
  Enabled: false

